name: CI

on: push

jobs:
  rubocop:
    runs-on: ubuntu-latest
    container: ruby:2.7.0
    steps:
      - uses: actions/checkout@v1
      - name: Install rubocop
        run: |
          gem install rubocop -v '0.80.0'
      - name: Run rubocop
        run: rubocop
